name: Manual Yocto Build
on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Config file path (e.g., kas/rockchip/scb600-openwrt.yml)'
        required: true
        default: 'kas/rockchip/scb600-openwrt.yml'
      clean_build:
        description: 'Perform full clean rebuild'
        type: boolean
        default: false

env:
  KAS_BUILD_DIR: build
  USER_UID: 1001
  USER_GID: 1001

jobs:
  yocto-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/siemens/kas/kas-isar:latest
      options: --user root

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Initialize Build Environment
      run: |
        mkdir -p ${{ env.KAS_BUILD_DIR }}
        chown -R ${{ env.USER_UID }}:${{ env.USER_GID }} ${{ env.KAS_BUILD_DIR }}

    - name: Clean Build Preparation
      if: ${{ inputs.clean_build }}
      run: |
        rm -rf ${{ env.KAS_BUILD_DIR }}/*
        kas prune --worktree-dir ${{ env.KAS_BUILD_DIR }}

    - name: Execute Yocto Build
      run: |
        kas build ${{ inputs.config }} 

    - name: Cache Management
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.KAS_BUILD_DIR }}/downloads
          ${{ env.KAS_BUILD_DIR }}/sstate-cache
        key: ${{ runner.os }}-${{ hashFiles('external_layer.sha') }}-${{ hashFiles(inputs.config) }}

    - name: Package Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: yocto-images
        path: ${{ env.KAS_BUILD_DIR }}/tmp/deploy/images/**/*
        retention-days: 3
        include-hidden-files: true
