name: Matrix Yocto Builder
on:
  push:
    branches: [ master ]
    paths:
      - 'kas/**'           # Trigger on config changes
      - 'meta-*/**'        # Trigger on layer updates
      - 'recipes-*/**'     # Trigger on recipe modifications
      - '!.github/**'      # Exclude workflow changes

env:
  KAS_BUILD_DIR: build
  USER_UID: 1001
  USER_GID: 1001

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/siemens/kas/kas:latest
      options: --user root
    strategy:
      matrix:
        config: 
          - kas/rockchip/scb600-openwrt.yml
          - kas/nxp/ls1046apscb-dev.yml
          - kas/picocom/pc805-dev.yml
      fail-fast: false

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Initialize Build Environment
      run: |
        mkdir -p ${{ env.KAS_BUILD_DIR }}
        chown -R ${{ env.USER_UID }}:${{ env.USER_GID }} ${{ env.KAS_BUILD_DIR }}

    - name: Build Image
      run: |
        kas build ${{ matrix.config }}

    - name: Layer State Cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.KAS_BUILD_DIR }}/downloads
          ${{ env.KAS_BUILD_DIR }}/sstate-cache
        key: ${{ runner.os }}-${{ matrix.config }}-${{ hashFiles(matrix.config) }}

    - name: Store Output Images
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.config | basename }}
        path: ${{ env.KAS_BUILD_DIR }}/tmp/deploy/images/**/*
        retention-days: 3
        include-hidden-files: true

    - name: Build Verification
      run: |
        kas dump ${{ matrix.config }}
        kas shell ${{ matrix.config }} -c "bitbake-layers show-layers"
